[package]
name = "mariadb-proxy"
version = "0.1.0"
authors = ["Raymond Cheng <me@raymondcheng.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
env_logger = "0.7.1"
futures = "0.3"
log = "0.4.0"
mysql_async = "0.21.1"
sqlparser = "0.5.0"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
abci = "0.6.4"