version: "3"

services:
  proxy:
    image: rust
    container_name: proxy
    command: /bin/bash -c "while true; do sleep 200; echo 'TERMINAL is up'; done"
    volumes:
      - "./:/code"
    working_dir: /code
    networks:
      - sqlproxy
      - sqlproxybackend
    depends_on:
      - mariadb-server
      - postgres-server

  mariadb-server:
    image: mariadb
    container_name: mariadb-server
    restart: always
    volumes:
      - ./docker/mariadb-server:/docker
    networks:
      - sqlproxybackend
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=testpassword
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword

  postgres-server:
    image: postgres
    container_name: postgres-server
    restart: always
    networks:
      - sqlproxybackend
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=testpassword

  adminer:
    image: adminer
    container_name: adminer 
    restart: always
    networks:
      - sqlproxybackend
    ports:
      - 8080:8080
    links:
      - mariadb-server
      - postgres-server
      - proxy

networks:
  sqlproxy:
    driver: bridge
  sqlproxybackend:
    driver: bridge
