version: "3"

services:
  mariadb-server:
    image: mariadb
    container_name: mariadb-server
    restart: always
    volumes:
      - ./docker/mariadb-server:/docker
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=testpassword
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword

  postgres-server:
    image: postgres
    container_name: postgres-server
    restart: always
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=testpassword

  adminer:
    image: adminer
    container_name: adminer 
    restart: always
    ports:
      - 8080:8080
    links:
      - mariadb-server
      - postgres-server
      - proxy

  proxy:
    image: rust
    container_name: proxy
    command: /bin/bash -c "while true; do sleep 200; echo 'TERMINAL is up'; done"
    volumes:
      - "./:/code"
    working_dir: /code
    links:
      - mariadb-server
      - postgres-server

  tendermint:
    image: tendermint/tendermint:v0.32.8
    container_name: tendermint-node
    entrypoint: /bin/sh -c "tendermint init && tendermint unsafe_reset_all && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://proxy:26658 --rpc.laddr=tcp://0.0.0.0:26657"
    volumes:
      - "/tmp/tendermint:/tendermint"
    links:
      - mariadb-server
      - postgres-server
      - proxy

  mediawiki:
    image: mediawiki
    container_name: mediawiki
    restart: always
    ports:
      - 8888:80
    links:
      - proxy
      - mariadb-server
    volumes:
      - /var/www/html/images
      - ./docker/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  discourse:
    image: 'bitnami/discourse:2'
    ports:
      - '80:3000'
    depends_on:
      - postgres-server
      - redis
    environment:
      - POSTGRESQL_HOST=postgres-server
      - POSTGRESQL_ROOT_USER=root
      - POSTGRESQL_ROOT_PASSWORD=testpassword
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=root
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=testpassword
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=root
      - DISCOURSE_POSTGRESQL_PASSWORD=testpassword
      - DISCOURSE_HOSTNAME=localhost
      
  sidekiq:
    image: 'bitnami/discourse:2'
    depends_on:
      - discourse
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=root
      - DISCOURSE_POSTGRESQL_PASSWORD=testpassword
      - DISCOURSE_HOST=discourse
      - DISCOURSE_PORT=3000
      - DISCOURSE_HOSTNAME=localhost